name: TodoMVC Pipeline

on: 
  push:
    branches:
      - master

env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  prepare-build-test:
    runs-on: ubuntu-latest

    steps:      
    
    - uses: actions/checkout@master

    - name: Github Info
      run: |
        echo "GITHUB_ACTION: $GITHUB_ACTION"
        echo "GITHUB_ACTOR: $GITHUB_ACTOR"
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
        echo "github.event_name: ${{ github.event_name }}"
        cat $GITHUB_EVENT_PATH

    - name: build
      run: |
        cd $GITHUB_WORKSPACE/examples/vue        
        export LOWERCASE_REPOSITORY=$(echo "${GITHUB_REPOSITORY}" | tr "[:upper:]" "[:lower:]")
        export IMAGE_NAME="docker.pkg.github.com/${LOWERCASE_REPOSITORY}/todomvc:v${GITHUB_SHA}"
        docker build -t $IMAGE_NAME .

    - name: publish
      run: |
        export OWNER="${GITHUB_REPOSITORY%/*}"
        export LOWERCASE_REPOSITORY=$(echo "${GITHUB_REPOSITORY}" | tr "[:upper:]" "[:lower:]")
        export IMAGE_NAME="docker.pkg.github.com/${LOWERCASE_REPOSITORY}/todomvc:v${GITHUB_SHA}"
        echo "owner: ${OWNER}"
        echo "token: ${GITHUB_TOKEN}"
        echo "repo: ${GITHUB_REPOSITORY}"
        echo "version: ${VERSION}"
        docker login -u ${OWNER} -p ${GITHUB_TOKEN} docker.pkg.github.com
        docker push $IMAGE_NAME
